site_name: "Test-Suite"
site_description: "External testing tools for the OQTOPUS quantum computing platform"
repo_name: test-suite
repo_url: "https://github.com/oqtopus-team/test-suite"

nav:
  - Home: index.md
  - Endurance Test: endurance-test/README.md
  - Scenario Tests:
      - Overview: scenario-tests/README.md
      - Setup: scenario-tests/setup/README.md
      - Estimation Job: scenario-tests/estimation-job/README.md
      - Multi-Programming (MP) Job: scenario-tests/mp-job/README.md
      - Sampling Job: scenario-tests/sampling-job/README.md
      - SSE Job: scenario-tests/sse-job/README.md
  - Developer Guidelines:
      - Setup Development Environment: developer_guidelines/setup.md
      - Development Flow: developer_guidelines/development_flow.md
      - Adding New Tests: developer_guidelines/adding_new_tests.md
      - How to Contribute: CONTRIBUTING.md
      - Code of Conduct: "https://github.com/oqtopus-team/.github/blob/main/CODE_OF_CONDUCT.md"
      - Security: "https://github.com/oqtopus-team/.github/blob/main/SECURITY.md"

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: asset/oqtopus-black_symbol.svg
  favicon: asset/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.follow
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - include-markdown

extra_css:
  - "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
  - "css/custom.css"
