site_name: Test-Suite Documentation
repo_url: https://github.com/qiqb-osaka/test-suite
repo_name: GitHub
theme:
  name: material
plugins:
  - search
  - include-markdown
nav:
  - Home: index.md
  - Endurance Test: endurance-test/README.md
  - Scenario Tests:
      - Overview: scenario-tests/README.md
      - Device: scenario-tests/device/README.md
      - Estimation Job: scenario-tests/estimation-job/README.md
      - Multi-Programming (MP) Job: scenario-tests/mp-job/README.md
      - Sampling Job: scenario-tests/sampling-job/README.md
      - SSE Job: scenario-tests/sse-job/README.md
