name: Docs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync --extra dev

      - name: Copy assets
        run: cp -r asset docs/

      - name: Build
        run: uv run mkdocs build

      - name: Zip artifact
        run: zip -r site.zip site

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Deploy to AWS Amplify
        run: |
          # 1. Create a new deployment and get the upload URL and Job ID
          DEPLOYMENT_INFO=$(aws amplify create-deployment --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main)
          JOB_ID=$(echo $DEPLOYMENT_INFO | jq -r '.jobId')
          UPLOAD_URL=$(echo $DEPLOYMENT_INFO | jq -r '.zipUploadUrl')

          echo "Job ID: $JOB_ID"

          # 2. Upload the zip file
          curl -X PUT -T "site.zip" "$UPLOAD_URL"

          # 3. Start the deployment
          aws amplify start-deployment --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main --job-id $JOB_ID
