name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      # Specify the default branch of your repository (e.g., main or develop)
      - main
      # - develop

#Permissions are required for PRs by dependabot.
permissions:
  pull-requests: write
  contents: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Extract commit messages
        run: |
          COMMITS=$(git log --format=%B origin/${{ github.event.pull_request.base.ref }}..HEAD)
          echo "$COMMITS"
          echo "$COMMITS" > commits.txt

      - name: Debug - Print commits
        run: cat commits.txt

      - name: Add labels based on commit messages
        uses: actions/github-script@v9
        with:
          script: |
            const fs = require('fs');

            const prefixToLabel = {
              feat: 'feature',
              fix: 'bugfix',
              docs: 'documentation',
              style: 'style',
              refactor: 'refactor',
              test: 'test',
              ci: 'ci',
              chore: 'chore',
            };

            const commits = fs.readFileSync('commits.txt', 'utf8').split('\n');
            const labels = new Set();
            for (const commit of commits) {
              for (const [prefix, label] of Object.entries(prefixToLabel)) {
                if (commit.startsWith(prefix)) {
                  labels.add(label);
                  break;
                }
              }
            }

            const uniqueLabels = [...labels];
            console.log('Unique labels:', uniqueLabels);

            if (uniqueLabels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: uniqueLabels,
              });
            }

      - name: Assign PR creator
        uses: actions/github-script@v9
        with:
          script: |
            await github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.actor]
            })
