name: Scenario Test

on:
    workflow_dispatch:
    schedule:
        - cron: "*/10 * * * *"

jobs:
    run-scenario-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./scenario-tests
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install runn
              run: |
                  curl -sL https://github.com/k1LoW/runn/releases/download/v0.95.0/runn_0.95.0_linux_amd64.tar.gz | tar xz
                  sudo mv runn /usr/local/bin/runn

            - name: Install task
              run: |
                  curl -sL https://taskfile.dev/install.sh | sh
                  sudo mv bin/task /usr/local/bin/task

            - name: Run all scenario tests
              env:
                  USER_API_ENDPOINT: ${{ secrets.USER_API_ENDPOINT }}
                  Q_API_TOKEN: ${{ secrets.Q_API_TOKEN }}
              run: task runn-all
