name: Scenario Test

on:
    workflow_dispatch:
    schedule:
        - cron: "*/10 * * * *"
    pull_request:

jobs:
    run-scenario-test:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./scenario-tests
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install runn
              run: |
                  gh release download v0.95.0 --repo k1LoW/runn --pattern '*linux_amd64.tar.gz'
                  tar xzf runn_0.95.0_linux_amd64.tar.gz
                  sudo mv runn /usr/local/bin/runn
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Install task
              run: |
                  curl -sL https://taskfile.dev/install.sh | sh
                  sudo mv bin/task /usr/local/bin/task

            - name: Run all scenario tests
              env:
                  USER_API_ENDPOINT: ${{ secrets.USER_API_ENDPOINT }}
                  Q_API_TOKEN: ${{ secrets.Q_API_TOKEN }}
              run: task runn-all
