name: Scenario Test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *"
  pull_request:

jobs:
  run-scenario-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scenario-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.49.1

      - name: Install runn
        uses: k1LoW/gh-setup@v1
        with:
           repo: k1LoW/runn
           version: v1.8.2

      - name: Run scenario tests (non-SSE)
        env:
          USER_API_ENDPOINT: ${{ secrets.USER_API_ENDPOINT }}
          Q_API_TOKEN: ${{ secrets.Q_API_TOKEN }}
          DEVICE_ID: ${{ secrets.DEVICE_ID }}
        run: |
          task runn-non-sse
